#
# Travis Setup
#

# use ubuntu trusty for newer version of nodejs, used for JS testing
dist: trusty

# faster builds on new travis setup not using sudo
# temporary disable, see https://github.com/travis-ci/travis-ci/issues/6842
#sudo: false
sudo: required
group: edge

#
# Test Matrix
#
language: php

env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0

services:
  - memcached
  - redis-server
  - mysql
  - postgresql

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.npm

# try running against postgres 9.6
addons:
  postgresql: "9.6"
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

matrix:
  fast_finish: true
  include:
    - php: 7.2

    # run tests coverage on PHP 7.1
    - php: 7.1
      env: TASK_TESTS_COVERAGE=1

    - php: nightly

  allow_failures:
    - php: nightly

install:
  - |
    if [[ $TASK_TESTS_COVERAGE != 1 && $TRAVIS_PHP_VERSION != hhv* ]]; then
      # disable xdebug for performance reasons when code coverage is not needed. note: xdebug on hhvm is disabled by default
      phpenv config-rm xdebug.ini || echo "xdebug is not installed"
    fi

  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer install $DEFAULT_COMPOSER_FLAGS
  - composer run-script post-root-package-install
  - composer run-script post-create-project-cmd
  - composer run-script post-autoload-dump

before_script:
  # show some versions and env information
  - php --version
  - composer --version
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      php -r "echo INTL_ICU_VERSION . \"\n\";"
      php -r "echo INTL_ICU_DATA_VERSION . \"\n\";"
      psql --version
      mysql --version
    fi

  # initialize databases
  - |
    if [ $TASK_TESTS_PHP == 1 ]; then
      travis_retry mysql -e 'CREATE DATABASE `homestead`;';
      mysql -e "SET GLOBAL sql_mode = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION';";
      mysql -e "CREATE USER 'homestead'@'localhost' IDENTIFIED WITH mysql_native_password;";
      mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'homestead'@'localhost' WITH GRANT OPTION;";
      psql -U postgres -c 'CREATE DATABASE homestead;';
    fi
  # enable code coverage
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      PHPUNIT_FLAGS="--coverage-clover=coverage.clover"
    fi
  # Disable DEPRECATE messages during PHPUnit initialization on PHP 7.2. To fix them, PHPUnit should be updated to 6.*
  # For Yii2 tests, messages will be enabled by tests/bootstrap.php
  - |
    if [ $TRAVIS_PHP_VERSION == 7.2 ]; then
      echo 'Disabled DEPRECATED notifications for PHP 7.2';
      echo 'error_reporting = E_ALL & ~E_DEPRECATED' >> /tmp/php-config.ini;
      phpenv config-add /tmp/php-config.ini;
    fi

script:
  # PHP tests
  - vendor/bin/phpunit --verbose $PHPUNIT_FLAGS

after_script:
  - |
    if [ $TASK_TESTS_COVERAGE == 1 ]; then
      travis_retry wget https://scrutinizer-ci.com/ocular.phar
      php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    fi
